# Generated by Django 5.2.1 on 2025-05-15 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ambiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sig', models.IntegerField(unique=True)),
                ('descricao', models.CharField(max_length=200)),
                ('ni', models.CharField(max_length=50)),
                ('responsavel', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sensores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor', models.CharField(max_length=50)),
                ('mac_address', models.CharField(max_length=20)),
                ('unidade_med', models.CharField(max_length=20)),
                ('latitude', models.CharField(max_length=100)),
                ('longitude', models.FloatField()),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('timestamp', models.IntegerField()),
                ('ambiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ambiente')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sensores')),
            ],
        ),
    ]
