# Generated by Django 5.2.1 on 2025-05-23 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_sensores_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensores',
            name='tipo',
            field=models.CharField(choices=[('temperatura', 'Temperatura'), ('umidade', 'Umidade'), ('luminosidade', 'Luminosidade'), ('contador', 'Contador')], default=models.CharField(max_length=50), max_length=30),
        ),
    ]
