# Generated by Django 5.2.1 on 2025-05-23 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_sensores_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historico',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
